Importing numpy module

In [1]:
import numpy as np

Ndarray -> The heart of the library.
ndarray stands for n-dimensional array, which is a homogeneous array

Creating an array, and understand its attributes.

In [2]:
#creating a 1D array
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
#checking the type of array a.
type(a)

numpy.ndarray

Array attributes:
1) dtype
2) ndim
3) size
4) shape
5) itemsize
6) data

In [4]:
a.dtype #returns the data type of the array.

dtype('int32')

In [5]:
a.shape #returns the shape of the array in a tuple. here it is (3 x 1) i.e (3,) in python.

(3,)

In [6]:
a.ndim #returns the dimension of the array/matrix.

1

In [7]:
a.size #returns the size or total no. of elements in the array.

3

In [8]:
a.itemsize #returns the size of each item in bytes ( for int the size is 4 bytes )

4

In [9]:
a.data #returns the buffer that contains actual elements of the array.

Creating Multidimensional arrays or matrices.

In [10]:
e1 = [1,2,3]
e2 = [4,5,6]
e3 = [7,8,9]
b = np.array([e1,e2,e3])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
c = np.array([e1,e2],dtype = complex) #defining the data type of c to complex no.s

In [12]:
print(c)

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]


In [13]:
d = np.array([e1,e2,e3], dtype = str) #defining the data type to be string.

In [14]:
print(d)

[['1' '2' '3']
 ['4' '5' '6']
 ['7' '8' '9']]


In [15]:
d.dtype

dtype('<U1')

In [16]:
d.dtype.name #to view the name of the '<U1' data type.

'str32'

Intrinsic Creation of an Array

In [17]:
#zeros function
np.zeros(3)

array([0., 0., 0.])

In [18]:
O = np.zeros((3,5), dtype = int)

In [19]:
print(O)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [20]:
O.dtype.name

'int32'

In [21]:
#ones function
np.ones(3)

array([1., 1., 1.])

In [22]:
P = np.ones((4,5))

In [23]:
print(P)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [24]:
P.dtype.name

'float64'

In [25]:
#arange function
np.arange(0,6) #returns a 1D array from 0 to 5

array([0, 1, 2, 3, 4, 5])

In [26]:
np.arange(5,10) #returns a 1D array from 5 to 9  

array([5, 6, 7, 8, 9])

In [27]:
np.arange(3,11).reshape(2,4) #reshape function changes the form the array, if the size is conformable.

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [28]:
np.arange(1,10,2) #returns an array, from 1 to 9, skipping a no.in between

array([1, 3, 5, 7, 9])

In [29]:
a = np.arange(1,4,0.5)

In [30]:
print("a = ",a)
print("Size of a = ",a.size)

a =  [1.  1.5 2.  2.5 3.  3.5]
Size of a =  6


In [31]:
#linspace function.
np.linspace(1,10,5) 

#returns an array, with elements from 1 to 10, with 5 elements in total, if size not mentioned, 50 is the default size.

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [32]:
a = np.linspace(23,65,10).reshape(2,5)
print(a,"\n")
print(np.trunc(a)) #truncating or cutting off the decimal values, if any.

[[23.         27.66666667 32.33333333 37.         41.66666667]
 [46.33333333 51.         55.66666667 60.33333333 65.        ]] 

[[23. 27. 32. 37. 41.]
 [46. 51. 55. 60. 65.]]


In [33]:
print(a.dtype)

float64


In [34]:
a.itemsize

8

In [35]:
a.shape

(2, 5)

In [36]:
np.log(a)

array([[3.13549422, 3.32022832, 3.47609869, 3.61091791, 3.72970145],
       [3.83586164, 3.93182563, 4.01938152, 4.09988474, 4.17438727]])

In [37]:
x = np.ceil(a)

In [38]:
y = np.floor(np.log(a))

In [39]:
print("x = \n", x)
print("y = \n", y)
print("x + y = \n", x+y)
print("x*y = \n", x*y) #this is the hadamard product(elementwise product of matrices)

x = 
 [[23. 28. 33. 37. 42.]
 [47. 51. 56. 61. 65.]]
y = 
 [[3. 3. 3. 3. 3.]
 [3. 3. 4. 4. 4.]]
x + y = 
 [[26. 31. 36. 40. 45.]
 [50. 54. 60. 65. 69.]]
x*y = 
 [[ 69.  84.  99. 111. 126.]
 [141. 153. 224. 244. 260.]]


In [40]:
a = np.ones((3,3))
b = np.array([e1,e2,e3])

In [41]:
a.dot(b) #normal matrix product

array([[12., 15., 18.],
       [12., 15., 18.],
       [12., 15., 18.]])

In [42]:
np.dot(a,b) #another method, of normal matrix product

array([[12., 15., 18.],
       [12., 15., 18.],
       [12., 15., 18.]])

In [43]:
c = np.random.random((3,2)) #using np.random module.

In [44]:
print(c)

[[0.05174171 0.47382964]
 [0.67075413 0.01217837]
 [0.19139096 0.40832041]]


In [45]:
x = np.arange(12).reshape((3,2,2))

In [46]:
x.ndim

3

In [47]:
x.shape

(3, 2, 2)

In [48]:
x.dtype

dtype('int32')

In [49]:
type(x)

numpy.ndarray

In [50]:
x.size

12

In [51]:
print(x)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [52]:
y = np.arange(16).reshape((2,4,2))

In [53]:
print(y)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]]


In [54]:
y.ndim

3

In [55]:
a = np.random.random((3,3))
print(a)

[[0.91514216 0.98461892 0.69106978]
 [0.61301989 0.34903376 0.99650284]
 [0.42889113 0.09963398 0.41836633]]


In [56]:
np.around(a,2) #rounding of to 2 decimal places atmost.

array([[0.92, 0.98, 0.69],
       [0.61, 0.35, 1.  ],
       [0.43, 0.1 , 0.42]])

In [57]:
np.round(a,2) #same as the around function, but easier to remember.

array([[0.92, 0.98, 0.69],
       [0.61, 0.35, 1.  ],
       [0.43, 0.1 , 0.42]])

In [58]:
np.apply_along_axis(np.sum, arr = np.round(a), axis = 1) #axis = 1 means, that the summing will be columnwise. 

array([3., 2., 0.])

In [59]:
b = np.arange(9).reshape((3,3))
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [60]:
np.apply_along_axis(np.sum, arr = b, axis = 1)

array([ 3, 12, 21])